version: '3.8'

services:

  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=process.env.MONGO_URI
      - JWT_SECRET=process.env.JWT_SECRET
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
